name: skin_analyser
description: "AI Skin Analyzer"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.3
  curved_navigation_bar: ^1.0.3
  cupertino_icons: ^1.0.2  
  tflite_flutter: ^0.12.1  # Use the latest compatible TF Lite plugin

  # ADD THESE TWO
  image_picker: ^1.0.7
  image: ^4.0.17
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/models/model_final.tflite
    - assets/images/
    - assets/models/class_indices.json
  